---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  labels:
    appname: busybox
    placement: busybox-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
